on:
  push:
    branches:
      - master
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: 📥 Install dependencies
        run: npm ci

      - name: 🏗️ Build project
        # run: npm run build
        run: npm run generate
        env:
          NUXT_PUBLIC_API_BASE: ${{ vars.NUXT_PUBLIC_API_BASE }}
          NUXT_APP_BASE_URL: ${{ vars.NUXT_APP_BASE_URL }}

      - name: ⚙️ Set rsync switches
        id: rsync_switches
        run: |
          EXCLUDES="--exclude='.env' --exclude='vendor/'"
          if echo "${{ github.event.head_commit.message }}" | grep -qi "\[force\]"; then
            echo "switches=-rlvz --delete --omit-dir-times --no-perms --ignore-times $EXCLUDES" >> $GITHUB_OUTPUT
            echo "Deploy FORÇADO: todos os arquivos serão enviados"
          else
            echo "switches=-rlvz --delete --omit-dir-times --no-perms $EXCLUDES" >> $GITHUB_OUTPUT
            echo "Deploy incremental: apenas arquivos alterados"
          fi

      - name: 📂 Deploy via rsync SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          rsync ${{ steps.rsync_switches.outputs.switches }} \
            -e "ssh -p ${{ secrets.SSH_PORT }} -i ~/.ssh/id_rsa" \
            ./.output/public/ \
            ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/home/identificatransito/htdocs/www.identificatransito.com.br/public/
