on: 
  push:
    branches:
      - master
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📦 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: 📥 Install dependencies
      run: npm ci
    
    - name: 🏗️ Build project
      # run: npm run build
      run: npm run generate
    
    - name: 📂 Deploy via rsync SSH
      uses: burnett01/rsync-deployments@7.0.1
      with:
        switches: -avzr --delete --omit-dir-times
        path: ./.output/public/
        remote_path: /home/identificatransito/htdocs/www.identificatransito.com.br/public/aprovacao/
        remote_host: ${{ secrets.SSH_HOST }}
        remote_user: ${{ secrets.SSH_USERNAME }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
        remote_port: ${{ secrets.SSH_PORT }}